import { beforeEach, describe, expect, it, vi } from "vitest";
import { ConnectorError } from "../../connectors/core/connector.errors.js";
import { AppError } from "../../middleware/errorHandler.js";
import { currentWorkspace } from "../workspaceContext.js";

const ids={watch:"507f1f77bcf86cd799439011",saved:"507f191e810c19729de860ea",run:"507f1f77bcf86cd799439012",event:"507f1f77bcf86cd799439013"};
const m=vi.hoisted(()=>({
 watchCreate:vi.fn(),watchFind:vi.fn(),watchFindOne:vi.fn(),watchUpdate:vi.fn(),watchDelete:vi.fn(),
 memberAggregate:vi.fn(),memberCount:vi.fn(),memberDeleteMany:vi.fn(),memberCreate:vi.fn(),memberDeleteOne:vi.fn(),memberFind:vi.fn(),
 stateFindOne:vi.fn(),stateUpdate:vi.fn(),stateDeleteMany:vi.fn(),stateDeleteOne:vi.fn(),stateFind:vi.fn(),
 savedExists:vi.fn(),savedFindOne:vi.fn(),savedFind:vi.fn(),runCreate:vi.fn(),runUpdate:vi.fn(),runFindById:vi.fn(),runFind:vi.fn(),
 eventUpdate:vi.fn(),eventFind:vi.fn(),eventFindOne:vi.fn()
}));
vi.mock("../../models/watchlist.model.js",()=>({WatchlistModel:{create:m.watchCreate,find:m.watchFind,findOne:m.watchFindOne,findOneAndUpdate:m.watchUpdate,findOneAndDelete:m.watchDelete,updateOne:m.watchUpdate},WatchlistMembershipModel:{aggregate:m.memberAggregate,countDocuments:m.memberCount,deleteMany:m.memberDeleteMany,create:m.memberCreate,deleteOne:m.memberDeleteOne,find:m.memberFind}}));
vi.mock("../../models/repositoryWatchState.model.js",()=>({RepositoryWatchStateModel:{findOne:m.stateFindOne,updateOne:m.stateUpdate,deleteMany:m.stateDeleteMany,deleteOne:m.stateDeleteOne,find:m.stateFind}}));
vi.mock("../../models/savedRepository.model.js",()=>({SavedRepositoryModel:{exists:m.savedExists,findOne:m.savedFindOne,find:m.savedFind}}));
vi.mock("../../models/watchCheckRun.model.js",()=>({WatchCheckRunModel:{create:m.runCreate,updateOne:m.runUpdate,findById:m.runFindById,find:m.runFind}}));
vi.mock("../../models/changeEvent.model.js",()=>({ChangeEventModel:{updateOne:m.eventUpdate,find:m.eventFind,findOne:m.eventFindOne}}));
import { WatchService } from "./watch.service.js";

const query=(value:unknown)=>({lean:vi.fn(async()=>value),sort:vi.fn(()=>({limit:vi.fn(()=>({lean:vi.fn(async()=>value)}))})),limit:vi.fn(()=>({lean:vi.fn(async()=>value)}))});
const watch=(overrides:Record<string,unknown>={})=>({_id:ids.watch,name:"Core",description:"Research",enabled:true,checkIntervalMinutes:60,lastCheckedAt:null,nextCheckAt:new Date("2026-01-01T00:00:00Z"),createdAt:new Date("2026-01-01T00:00:00Z"),updatedAt:new Date("2026-01-01T00:00:00Z"),...overrides});
const saved=(overrides:Record<string,unknown>={})=>({_id:ids.saved,source:"github",externalId:"1",fullName:"atlas/core",...overrides});
const item=(stars=1)=>({source:"github",sourceId:"1",sourceType:"repository",id:"github:1",title:"atlas/core",description:"desc",url:"https://example.test",author:null,metrics:{views:null,stars,forks:2,likes:null,comments:null,shares:null,watchers:3,openIssues:4},tags:["agents"],language:"TypeScript",createdAt:null,updatedAt:"2026-01-02T00:00:00Z",publishedAt:null,collectedAt:"2026-01-02T00:00:00Z",rawDataReference:null,provenance:{source:"github",sourceId:"1",sourceUrl:"https://example.test",connectorVersion:"1",requestId:"r",jobId:null,collectedAt:"2026-01-02T00:00:00Z"},metadata:{defaultBranch:"main",license:"MIT",archived:false,visibility:"public",pushedAt:"2026-01-02T00:00:00Z"}} as any);
const connector={enabled:true,fetchItem:vi.fn(async()=>({item:item(),rawItem:{},rateLimit:{}}))};
const registry={require:vi.fn(()=>connector)} as any;
const service=()=>new WatchService(registry,2);

beforeEach(()=>{vi.clearAllMocks();m.watchCreate.mockImplementation(async(input)=>({toObject:()=>({_id:ids.watch,createdAt:new Date(),updatedAt:new Date(),...input})}));m.watchFindOne.mockReturnValue(query(watch()));m.watchUpdate.mockReturnValue(query(watch()));m.watchDelete.mockReturnValue(query(watch()));m.memberCount.mockResolvedValue(0);m.memberAggregate.mockResolvedValue([]);m.memberDeleteMany.mockResolvedValue({deletedCount:1});m.memberCreate.mockResolvedValue({});m.memberDeleteOne.mockResolvedValue({deletedCount:1});m.stateDeleteMany.mockResolvedValue({deletedCount:1});m.stateDeleteOne.mockResolvedValue({deletedCount:1});m.stateUpdate.mockResolvedValue({});m.savedExists.mockResolvedValue({_id:ids.saved});m.savedFindOne.mockReturnValue(query(saved()));m.runCreate.mockResolvedValue({_id:ids.run});m.runUpdate.mockResolvedValue({});m.runFindById.mockReturnValue(query({_id:ids.run,watchlistId:ids.watch,status:"completed",checked:0,changed:0,unchanged:0,failed:0,rateLimited:0,safeErrors:[]}));m.eventUpdate.mockResolvedValue({});connector.fetchItem.mockResolvedValue({item:item(),rawItem:{},rateLimit:{}});});

describe("WatchService CRUD and membership",()=>{
 it("creates a watchlist with an immediately due schedule",async()=>{const result=await service().create({name:"Core",description:"",enabled:true,checkIntervalMinutes:15});expect(m.watchCreate).toHaveBeenCalledWith(expect.objectContaining({workspaceKey:"default",nextCheckAt:expect.any(Date)}));expect(result.name).toBe("Core");});
 it("updates watchlist fields",async()=>{await service().update(ids.watch,{name:"Updated"});expect(m.watchUpdate).toHaveBeenCalledWith(expect.objectContaining({workspaceKey:"default"}),{$set:{name:"Updated"}},{new:true});});
 it("enables and disables scheduling",async()=>{await service().update(ids.watch,{enabled:true});expect(m.watchUpdate.mock.calls[0][1].$set.nextCheckAt).toBeInstanceOf(Date);await service().update(ids.watch,{enabled:false});expect(m.watchUpdate.mock.calls[1][1].$set.nextCheckAt).toBeNull();});
 it("deletes memberships and state without deleting saved repositories",async()=>{await service().remove(ids.watch);expect(m.memberDeleteMany).toHaveBeenCalled();expect(m.stateDeleteMany).toHaveBeenCalled();expect(m.savedFindOne).not.toHaveBeenCalled();});
 it("adds a saved repository membership",async()=>{await service().addRepository(ids.watch,ids.saved);expect(m.memberCreate).toHaveBeenCalledWith(expect.objectContaining({workspaceKey:"default"}));});
 it("rejects duplicate membership",async()=>{m.memberCreate.mockRejectedValueOnce(Object.assign(new Error("duplicate"),{code:11000}));await expect(service().addRepository(ids.watch,ids.saved)).rejects.toMatchObject({status:409,code:"WATCHLIST_MEMBERSHIP_EXISTS"});});
 it("removes membership and watch state",async()=>{expect(await service().removeRepository(ids.watch,ids.saved)).toEqual({deleted:true});expect(m.memberDeleteOne).toHaveBeenCalled();expect(m.stateDeleteOne).toHaveBeenCalled();});
 it("rejects an unsaved repository",async()=>{m.savedExists.mockResolvedValueOnce(null);await expect(service().addRepository(ids.watch,ids.saved)).rejects.toMatchObject({status:404,code:"SAVED_REPOSITORY_NOT_FOUND"});});
 it("paginates watchlists with a stable ObjectId cursor",async()=>{const rows=[watch(),watch({_id:"507f1f77bcf86cd799439010"})];m.watchFind.mockReturnValue(query(rows));const result=await service().list({limit:1});expect(result).toMatchObject({hasMore:true,nextCursor:ids.watch});});
});

describe("WatchService checks",()=>{
 function setupCheck(previous:any=null,members=[{watchlistId:ids.watch,savedId:ids.saved}]){m.memberFind.mockReturnValue(query(members));m.stateFindOne.mockReturnValue(query(previous));}
 it("establishes the first baseline without a change event",async()=>{setupCheck();await service().execute(watch(),{_id:ids.run});expect(m.eventUpdate).not.toHaveBeenCalled();expect(m.stateUpdate).toHaveBeenCalledWith(expect.any(Object),expect.objectContaining({$set:expect.objectContaining({snapshot:expect.objectContaining({stars:1}),consecutiveFailures:0})}),{upsert:true});});
 it("records an unchanged successful check without an event",async()=>{setupCheck({snapshot:{stars:1,forks:2,watchers:3,openIssues:4,defaultBranch:"main",language:"TypeScript",license:"MIT",archived:false,visibility:"public",description:"desc",topics:["agents"],sourceUpdatedAt:"2026-01-02T00:00:00.000Z",pushedAt:"2026-01-02T00:00:00.000Z"},fingerprint:"old"});await service().execute(watch(),{_id:ids.run});expect(m.eventUpdate).not.toHaveBeenCalled();expect(m.runUpdate.mock.calls[0][1].$set).toMatchObject({checked:1,unchanged:1,changed:0});});
 it("inserts changes idempotently by run and saved repository",async()=>{setupCheck({snapshot:{stars:0},fingerprint:"old"});await service().execute(watch(),{_id:ids.run});expect(m.eventUpdate).toHaveBeenCalledWith({workspaceKey:"default",checkRunId:ids.run,savedId:ids.saved},expect.objectContaining({$setOnInsert:expect.objectContaining({changeTypes:expect.arrayContaining(["stars"])})}),{upsert:true});});
 it("exposes the documented event-before-state failure window",async()=>{setupCheck({snapshot:{stars:0},fingerprint:"old"});m.stateUpdate.mockRejectedValue(new Error("state write failed"));await expect(service().execute(watch(),{_id:ids.run})).rejects.toThrow("state write failed");expect(m.eventUpdate).toHaveBeenCalledTimes(1);expect(m.runUpdate).not.toHaveBeenCalled();});
 it.each([["rate_limited","rateLimited"],["timeout","failed"],["provider","failed"],["authentication","failed"],["not_found","failed"]] as const)("preserves baseline and creates no false event for %s",async(code,count)=>{setupCheck({snapshot:{stars:9},fingerprint:"valid"});connector.fetchItem.mockRejectedValueOnce(new ConnectorError("github",code,"safe",code==="rate_limited"||code==="timeout"));await service().execute(watch(),{_id:ids.run});expect(m.eventUpdate).not.toHaveBeenCalled();const stateSet=m.stateUpdate.mock.calls[0][1].$set;expect(stateSet).not.toHaveProperty("snapshot");expect(stateSet.lastError.code).toBe(code);expect(m.runUpdate.mock.calls[0][1].$set[count]).toBe(1);});
 it("completes partially and records exact result counts",async()=>{setupCheck({snapshot:{stars:0},fingerprint:"old"},[{savedId:ids.saved},{savedId:"507f1f77bcf86cd799439014"}]);m.savedFindOne.mockReturnValueOnce(query(saved())).mockReturnValueOnce(query(saved({_id:"507f1f77bcf86cd799439014"})));connector.fetchItem.mockResolvedValueOnce({item:item(1),rawItem:{},rateLimit:{}}).mockRejectedValueOnce(new ConnectorError("github","rate_limited","safe",true));await service().execute(watch(),{_id:ids.run});expect(m.runUpdate.mock.calls[0][1].$set).toMatchObject({status:"partially_complete",checked:2,changed:1,unchanged:0,failed:0,rateLimited:1,active:false});});
 it("calculates nextCheckAt from completion time",async()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-02-01T00:00:00Z"));setupCheck(null,[]);await service().execute(watch({checkIntervalMinutes:30}),{_id:ids.run});expect(m.watchUpdate.mock.calls[0][1].$set.nextCheckAt.toISOString()).toBe("2026-02-01T00:30:00.000Z");vi.useRealTimers();});
 it("runs a manual check and returns its durable run",async()=>{setupCheck(null,[]);const result=await service().startCheck(ids.watch,"request-1");expect(m.runCreate).toHaveBeenCalledWith(expect.objectContaining({requestId:"request-1",active:true,status:"running"}));expect(result.status).toBe("completed");});
 it("rejects an overlapping active run",async()=>{m.runCreate.mockRejectedValueOnce(Object.assign(new Error("duplicate"),{code:11000}));await expect(service().startCheck(ids.watch,"request-2")).rejects.toEqual(expect.objectContaining({status:409,code:"WATCHLIST_CHECK_IN_PROGRESS"}));});
 it("selects only a bounded set of due enabled watchlists",async()=>{const limit=vi.fn(()=>({lean:vi.fn(async()=>[watch(),watch({_id:"507f1f77bcf86cd799439010"})])}));m.watchFind.mockReturnValue({sort:vi.fn(()=>({limit}))});const subject=service();vi.spyOn(subject,"startCheck").mockResolvedValue({} as never);await subject.due(2,"worker");expect(m.watchFind).toHaveBeenCalledWith({enabled:true,nextCheckAt:{$lte:expect.any(Date)}});expect(limit).toHaveBeenCalledWith(2);expect(subject.startCheck).toHaveBeenCalledTimes(2);});
 it("runs due watchlists in their own workspace contexts",async()=>{const limit=vi.fn(()=>({lean:vi.fn(async()=>[watch({workspaceKey:"workspace-b"})])}));m.watchFind.mockReturnValue({sort:vi.fn(()=>({limit}))});const subject=service();const seen:string[]=[];vi.spyOn(subject,"startCheck").mockImplementation(async()=>{seen.push(currentWorkspace());return{} as never});await subject.due(1,"worker");expect(seen).toEqual(["workspace-b"]);});
});

describe("WatchService changes",()=>{
 it("paginates and applies every supported change filter",async()=>{const row={_id:ids.event,watchlistId:ids.watch,savedId:ids.saved,source:"github",externalId:"1",detectedAt:new Date(),changeTypes:["stars"],changes:{stars:{previous:1,current:2}}};m.eventFind.mockReturnValue(query([row,{...row,_id:"507f1f77bcf86cd799439014"}]));m.savedFind.mockReturnValue(query([saved({fullName:"atlas/core"})]));m.watchFind.mockReturnValue(query([watch()]));const from=new Date("2026-01-01"),to=new Date("2026-02-01");const result=await service().changes({limit:1,cursor:"507f1f77bcf86cd799439015",watchlistId:ids.watch,savedId:ids.saved,source:"github",changeType:"stars",from,to});expect(m.eventFind).toHaveBeenCalledWith(expect.objectContaining({workspaceKey:"default",source:"github",changeTypes:"stars",detectedAt:{$gte:from,$lte:to},_id:{$lt:expect.anything()}}));expect(result).toMatchObject({hasMore:true,nextCursor:ids.event});});
});
