import { currentWorkspace, runInWorkspace } from "../workspaceContext.js";
import { Types } from "mongoose";
import { ConnectorError } from "../../connectors/core/connector.errors.js";
import type { ConnectorRegistry } from "../../connectors/core/connectorRegistry.js";
import { AppError } from "../../middleware/errorHandler.js";
import { ChangeEventModel } from "../../models/changeEvent.model.js";
import { RepositoryWatchStateModel } from "../../models/repositoryWatchState.model.js";
import { SavedRepositoryModel } from "../../models/savedRepository.model.js";
import { WatchCheckRunModel } from "../../models/watchCheckRun.model.js";
import { WatchlistMembershipModel, WatchlistModel } from "../../models/watchlist.model.js";
import type { NormalizedItem } from "../../types/normalizedItem.js";
import { detectChanges, snapshotFingerprint, type RepositorySnapshot } from "./changeDetector.js";


const oid=(id:string,code="INVALID_ID")=>{if(!Types.ObjectId.isValid(id))throw new AppError(400,code,"Invalid identifier");return new Types.ObjectId(id);};
const date=(value:unknown)=>value instanceof Date?value.toISOString():value?new Date(String(value)).toISOString():null;
const serializeWatchlist=(row:any,count=0)=>({watchlistId:String(row._id),name:row.name,description:row.description,enabled:row.enabled,checkIntervalMinutes:row.checkIntervalMinutes,lastCheckedAt:date(row.lastCheckedAt),nextCheckAt:date(row.nextCheckAt),targetCount:count,createdAt:date(row.createdAt),updatedAt:date(row.updatedAt)});

export class WatchService {
  constructor(private readonly registry:ConnectorRegistry,private readonly concurrency=3){}
  async create(input:{name:string;description:string;enabled:boolean;checkIntervalMinutes:number}){const now=new Date();const row=await WatchlistModel.create({...input,workspaceKey: currentWorkspace(),nextCheckAt:input.enabled?now:null});return serializeWatchlist(row.toObject());}
  async list(input:{cursor?:string;limit:number}){const filter:any={workspaceKey: currentWorkspace()};if(input.cursor)filter._id={$lt:oid(input.cursor)};const rows=await WatchlistModel.find(filter).sort({_id:-1}).limit(input.limit+1).lean();const visible=rows.slice(0,input.limit);const counts=await WatchlistMembershipModel.aggregate([{$match:{workspaceKey: currentWorkspace(),watchlistId:{$in:visible.map(r=>r._id)}}},{$group:{_id:"$watchlistId",count:{$sum:1}}}]);const map=new Map(counts.map(c=>[String(c._id),c.count]));return{watchlists:visible.map(r=>serializeWatchlist(r,map.get(String(r._id))??0)),nextCursor:rows.length>input.limit?String(visible.at(-1)!._id):null,hasMore:rows.length>input.limit};}
  async get(id:string){const row=await WatchlistModel.findOne({_id:oid(id),workspaceKey: currentWorkspace()}).lean();if(!row)throw new AppError(404,"WATCHLIST_NOT_FOUND","Watchlist was not found");const count=await WatchlistMembershipModel.countDocuments({workspaceKey: currentWorkspace(),watchlistId:row._id});return serializeWatchlist(row,count);}
  async update(id:string,input:Record<string,unknown>){const update:any={...input};if(input.enabled===true)update.nextCheckAt=new Date();if(input.enabled===false)update.nextCheckAt=null;const row=await WatchlistModel.findOneAndUpdate({_id:oid(id),workspaceKey: currentWorkspace()},{$set:update},{new:true}).lean();if(!row)throw new AppError(404,"WATCHLIST_NOT_FOUND","Watchlist was not found");return serializeWatchlist(row,await WatchlistMembershipModel.countDocuments({workspaceKey: currentWorkspace(),watchlistId:row._id}));}
  async remove(id:string){const watchlistId=oid(id);const row=await WatchlistModel.findOneAndDelete({_id:watchlistId,workspaceKey: currentWorkspace()});if(!row)throw new AppError(404,"WATCHLIST_NOT_FOUND","Watchlist was not found");await Promise.all([WatchlistMembershipModel.deleteMany({workspaceKey: currentWorkspace(),watchlistId}),RepositoryWatchStateModel.deleteMany({workspaceKey: currentWorkspace(),watchlistId})]);return{deleted:true};}
  async addRepository(watchlistIdValue:string,savedIdValue:string){const watchlistId=oid(watchlistIdValue),savedId=oid(savedIdValue);await this.get(watchlistIdValue);if(!await SavedRepositoryModel.exists({_id:savedId,workspaceKey: currentWorkspace()}))throw new AppError(404,"SAVED_REPOSITORY_NOT_FOUND","Repository must be saved before it can be watched");try{await WatchlistMembershipModel.create({workspaceKey: currentWorkspace(),watchlistId,savedId});}catch(error:any){if(error?.code===11000)throw new AppError(409,"WATCHLIST_MEMBERSHIP_EXISTS","Repository is already in this watchlist");throw error;}return{watchlistId:watchlistIdValue,savedId:savedIdValue};}
  async removeRepository(watchlistIdValue:string,savedIdValue:string){const watchlistId=oid(watchlistIdValue),savedId=oid(savedIdValue);const result=await WatchlistMembershipModel.deleteOne({workspaceKey: currentWorkspace(),watchlistId,savedId});await RepositoryWatchStateModel.deleteOne({workspaceKey: currentWorkspace(),watchlistId,savedId});return{deleted:result.deletedCount===1};}
  async repositories(id:string,input:{cursor?:string;limit:number}){const watchlistId=oid(id);await this.get(id);const filter:any={workspaceKey: currentWorkspace(),watchlistId};if(input.cursor)filter.savedId={$lt:oid(input.cursor)};const memberships=await WatchlistMembershipModel.find(filter).sort({savedId:-1}).limit(input.limit+1).lean();const visible=memberships.slice(0,input.limit),ids=visible.map(m=>m.savedId);const [saved,states]=await Promise.all([SavedRepositoryModel.find({_id:{$in:ids},workspaceKey: currentWorkspace()}).lean(),RepositoryWatchStateModel.find({workspaceKey: currentWorkspace(),watchlistId,savedId:{$in:ids}}).lean()]);const savedMap=new Map(saved.map(r=>[String(r._id),r])),stateMap=new Map(states.map(r=>[String(r.savedId),r]));return{repositories:visible.flatMap(m=>{const r:any=savedMap.get(String(m.savedId));if(!r)return[];const s:any=stateMap.get(String(m.savedId));return[{savedId:String(r._id),source:r.source,externalId:r.externalId,fullName:r.fullName,lastCheckedAt:date(s?.lastCheckedAt),lastSuccessfulCheckAt:date(s?.lastSuccessfulCheckAt),consecutiveFailures:s?.consecutiveFailures??0,lastError:s?.lastError??null}];}),nextCursor:memberships.length>input.limit?String(visible.at(-1)!.savedId):null,hasMore:memberships.length>input.limit};}
  async startCheck(id:string,requestId:string){const watchlistId=oid(id);const watchlist:any=await WatchlistModel.findOne({_id:watchlistId,workspaceKey: currentWorkspace(),enabled:true}).lean();if(!watchlist)throw new AppError(404,"WATCHLIST_NOT_FOUND","Enabled watchlist was not found");let run:any;try{run=await WatchCheckRunModel.create({workspaceKey: currentWorkspace(),watchlistId,status:"running",startedAt:new Date(),requestId,active:true});}catch(error:any){if(error?.code===11000)throw new AppError(409,"WATCHLIST_CHECK_IN_PROGRESS","A check is already running for this watchlist");throw error;}await this.execute(watchlist,run);return this.serializeRun(await WatchCheckRunModel.findById(run._id).lean());}
  async execute(watchlist:any,run:any){const memberships=await WatchlistMembershipModel.find({workspaceKey: currentWorkspace(),watchlistId:watchlist._id}).lean();let cursor=0;const results:('changed'|'unchanged'|'failed'|'rateLimited')[]=[];const errors:{savedId:string;code:string}[]=[];const worker=async()=>{while(cursor<memberships.length){const membership=memberships[cursor++];const outcome=await this.checkOne(watchlist,membership,run._id,errors);results.push(outcome);}};await Promise.all(Array.from({length:Math.min(this.concurrency,memberships.length)},worker));const failed=results.filter(v=>v==='failed').length,rateLimited=results.filter(v=>v==='rateLimited').length,changed=results.filter(v=>v==='changed').length,unchanged=results.filter(v=>v==='unchanged').length;const completedAt=new Date(),status=failed||rateLimited?(changed||unchanged?'partially_complete':'failed'):'completed';await WatchCheckRunModel.updateOne({_id:run._id},{$set:{status,completedAt,active:false,checked:results.length,failed,rateLimited,changed,unchanged,safeErrors:errors}});await WatchlistModel.updateOne({_id:watchlist._id},{$set:{lastCheckedAt:completedAt,nextCheckAt:new Date(completedAt.getTime()+watchlist.checkIntervalMinutes*60000)}});}
  private async checkOne(watchlist:any,membership:any,runId:Types.ObjectId,errors:{savedId:string;code:string}[]):Promise<'changed'|'unchanged'|'failed'|'rateLimited'>{const checkedAt=new Date();const saved:any=await SavedRepositoryModel.findOne({_id:membership.savedId,workspaceKey: currentWorkspace()}).lean();if(!saved){errors.push({savedId:String(membership.savedId),code:"saved_repository_missing"});return"failed";}try{const connector=this.registry.require(saved.source);if(!connector.enabled)throw new ConnectorError(saved.source,"disabled","Connector disabled",false);const locator=saved.source==="gitlab"?saved.externalId:saved.fullName;const result=await connector.fetchItem({sourceType:"repository",locator},{requestId:`watch:${runId}`,jobId:null});const snapshot=this.snapshot(result.item),fingerprint=snapshotFingerprint(snapshot);const previous:any=await RepositoryWatchStateModel.findOne({workspaceKey: currentWorkspace(),watchlistId:watchlist._id,savedId:saved._id}).lean();const detected=previous?.snapshot?detectChanges(previous.snapshot as RepositorySnapshot,snapshot):{changeTypes:[],changes:{}};if(detected.changeTypes.length)await ChangeEventModel.updateOne({workspaceKey: currentWorkspace(),checkRunId:runId,savedId:saved._id},{$setOnInsert:{watchlistId:watchlist._id,source:saved.source,externalId:saved.externalId,detectedAt:checkedAt,...detected,previousFingerprint:previous.fingerprint,currentFingerprint:fingerprint}},{upsert:true});await RepositoryWatchStateModel.updateOne({workspaceKey: currentWorkspace(),watchlistId:watchlist._id,savedId:saved._id},{$set:{source:saved.source,externalId:saved.externalId,snapshot,fingerprint,lastCheckedAt:checkedAt,lastSuccessfulCheckAt:checkedAt,lastError:null,consecutiveFailures:0}},{upsert:true});return detected.changeTypes.length?"changed":"unchanged";}catch(error){const code=error instanceof ConnectorError?error.code:"provider";await RepositoryWatchStateModel.updateOne({workspaceKey: currentWorkspace(),watchlistId:watchlist._id,savedId:saved._id},{$set:{source:saved.source,externalId:saved.externalId,lastCheckedAt:checkedAt,lastError:{code,category:"provider",occurredAt:checkedAt}},$inc:{consecutiveFailures:1}},{upsert:true});errors.push({savedId:String(saved._id),code});return code==="rate_limited"?"rateLimited":"failed";}}
  private snapshot(item:NormalizedItem):RepositorySnapshot{const m=item.metadata;return{stars:item.metrics.stars,forks:item.metrics.forks,watchers:item.metrics.watchers,openIssues:item.metrics.openIssues,defaultBranch:typeof m.defaultBranch==='string'?m.defaultBranch:null,language:item.language,license:typeof m.license==='string'?m.license:null,archived:typeof m.archived==='boolean'?m.archived:null,visibility:typeof m.visibility==='string'?m.visibility:null,description:item.description,topics:item.tags,sourceUpdatedAt:item.updatedAt,pushedAt:typeof m.pushedAt==='string'?m.pushedAt:null};}
  async runs(id:string,input:{cursor?:string;limit:number}){const filter:any={workspaceKey: currentWorkspace(),watchlistId:oid(id)};if(input.cursor)filter._id={$lt:oid(input.cursor)};const rows=await WatchCheckRunModel.find(filter).sort({_id:-1}).limit(input.limit+1).lean();const visible=rows.slice(0,input.limit);return{runs:visible.map(r=>this.serializeRun(r)),nextCursor:rows.length>input.limit?String(visible.at(-1)!._id):null,hasMore:rows.length>input.limit};}
  private serializeRun(row:any){return{runId:String(row._id),watchlistId:String(row.watchlistId),status:row.status,startedAt:date(row.startedAt),completedAt:date(row.completedAt),checked:row.checked,changed:row.changed,unchanged:row.unchanged,failed:row.failed,rateLimited:row.rateLimited,errors:row.safeErrors??[]};}
  async due(limit:number,requestId:string){const rows=await WatchlistModel.find({enabled:true,nextCheckAt:{$lte:new Date()}}).sort({nextCheckAt:1,_id:1}).limit(limit).lean();const runs=[];for(const row of rows){try{runs.push(await runInWorkspace(row.workspaceKey,()=>this.startCheck(String(row._id),requestId)));}catch(error){if(!(error instanceof AppError&&error.code==="WATCHLIST_CHECK_IN_PROGRESS"))throw error;}}return runs;}
  async changes(input:any){const filter:any={workspaceKey: currentWorkspace()};for(const key of ['watchlistId','savedId'])if(input[key])filter[key]=oid(input[key]);if(input.source)filter.source=input.source;if(input.changeType)filter.changeTypes=input.changeType;if(input.cursor)filter._id={$lt:oid(input.cursor)};if(input.from||input.to)filter.detectedAt={...(input.from?{$gte:input.from}:{}),...(input.to?{$lte:input.to}:{})};const rows=await ChangeEventModel.find(filter).sort({_id:-1}).limit(input.limit+1).lean();const visible=rows.slice(0,input.limit);const [saved,watchlists]=await Promise.all([SavedRepositoryModel.find({workspaceKey:currentWorkspace(),_id:{$in:visible.map(r=>r.savedId)}}).lean(),WatchlistModel.find({workspaceKey:currentWorkspace(),_id:{$in:visible.map(r=>r.watchlistId)}}).lean()]);const sm=new Map(saved.map(r=>[String(r._id),r.fullName])),wm=new Map(watchlists.map(r=>[String(r._id),r.name]));return{changes:visible.map((r:any)=>({changeId:String(r._id),watchlistId:String(r.watchlistId),watchlistName:wm.get(String(r.watchlistId))??"Deleted watchlist",savedId:String(r.savedId),repositoryName:sm.get(String(r.savedId))??r.externalId,source:r.source,externalId:r.externalId,detectedAt:date(r.detectedAt),changeTypes:r.changeTypes,changes:r.changes})),nextCursor:rows.length>input.limit?String(visible.at(-1)!._id):null,hasMore:rows.length>input.limit};}
  async change(id:string){const row:any=await ChangeEventModel.findOne({_id:oid(id),workspaceKey: currentWorkspace()}).lean();if(!row)throw new AppError(404,"CHANGE_NOT_FOUND","Change event was not found");return{changeId:String(row._id),watchlistId:String(row.watchlistId),savedId:String(row.savedId),source:row.source,externalId:row.externalId,detectedAt:date(row.detectedAt),changeTypes:row.changeTypes,changes:row.changes};}
}
