import { describe, expect, it, vi } from "vitest";
import { AnalyticsService } from "./analytics.service.js";

const range = { from: new Date("2026-01-01T00:00:00Z"), to: new Date("2026-01-31T00:00:00Z"), limit: 10 };
const model = (counts: number[] = [], aggregates: any[][] = []) => ({ countDocuments: vi.fn(async () => counts.shift() ?? 0), aggregate: vi.fn(async () => aggregates.shift() ?? []) });
const dependencies = (overrides: Record<string, any> = {}) => ({ ChangeEventModel:model(),CollectionMembershipModel:model(),CollectionModel:model(),RepositoryResultModel:model(),SavedRepositoryModel:model(),SearchJobModel:model(),WatchCheckRunModel:model(),WatchlistMembershipModel:model(),WatchlistModel:model(),...overrides });

describe("AnalyticsService", () => {
  it("returns persisted summary counts and dates", async () => {
    const service = new AnalyticsService(dependencies({ SearchJobModel:model([12,8,2],[[{value:new Date("2026-01-20") }]]),RepositoryResultModel:model([42]),SavedRepositoryModel:model([5],[[{value:new Date("2026-01-21") }]]),CollectionModel:model([3]),WatchlistModel:model([4,3]),ChangeEventModel:model([7],[[{value:new Date("2026-01-22") }]]),WatchlistMembershipModel:model([],[[{count:2}]]) }));
    expect(await service.summary(range)).toMatchObject({totalSearchJobs:12,completedSearchJobs:8,partiallyCompletedSearchJobs:2,totalCollectedRepositories:42,savedRepositories:5,collections:3,watchlists:4,recentChanges:7,enabledWatchlists:3,monitoredRepositories:2});
  });
  it("returns an honest empty summary", async () => expect(await new AnalyticsService(dependencies()).summary(range)).toMatchObject({totalSearchJobs:0,totalCollectedRepositories:0,savedRepositories:0,recentChanges:0,monitoredRepositories:0,lastChangeAt:null}));
  it("computes source distribution and percentages", async () => { const value=await new AnalyticsService(dependencies({RepositoryResultModel:model([],[[{_id:"github",count:3},{_id:"gitlab",count:1}]])})).sources(); expect(value).toMatchObject({total:4,sources:[{source:"github",count:3,percentage:75},{source:"gitlab",count:1,percentage:25}]}); });
  it("handles zero-total source percentages", async () => expect((await new AnalyticsService(dependencies()).sources()).sources).toEqual([]));
  it("returns bounded language distribution", async () => { const value=await new AnalyticsService(dependencies({RepositoryResultModel:model([],[[{_id:"TypeScript",count:5},{_id:"Go",count:2}]])})).languages(1); expect(value.languages).toEqual([{language:"TypeScript",count:5,percentage:71.43}]); });
  it("represents unknown languages rather than excluding them", async () => { const value=await new AnalyticsService(dependencies({RepositoryResultModel:model([],[[{_id:"Unknown",count:2}]])})).languages(10); expect(value).toMatchObject({excludedCount:0,languages:[{language:"Unknown",count:2,percentage:100}]}); });
  it("aggregates saved sources without notes", async () => { const value=await new AnalyticsService(dependencies({SavedRepositoryModel:model([2],[[{_id:"github",count:2}],[],[]]),CollectionMembershipModel:model([], [[]])})).saved(10); expect(value.bySource).toEqual([{source:"github",count:2,percentage:100}]); expect(value).not.toHaveProperty("notes"); });
  it("aggregates saved languages", async () => { const value=await new AnalyticsService(dependencies({SavedRepositoryModel:model([2],[[],[{_id:"Rust",count:2}],[]]),CollectionMembershipModel:model([], [[]])})).saved(10); expect(value.byLanguage[0]).toEqual({language:"Rust",count:2,percentage:100}); });
  it("aggregates bounded saved tags", async () => { const saved=model([1],[[],[],[{_id:"agents",count:3}]]); const value=await new AnalyticsService(dependencies({SavedRepositoryModel:saved,CollectionMembershipModel:model([], [[]])})).saved(5); expect(value.topTags).toEqual([{tag:"agents",count:3}]); expect(saved.aggregate.mock.calls[2][0]).toContainEqual({$limit:5}); });
  it("computes collection usage", async () => { const value=await new AnalyticsService(dependencies({SavedRepositoryModel:model([4],[[],[],[]]),CollectionMembershipModel:model([],[[{repositories:3,memberships:6}]])})).saved(10); expect(value).toMatchObject({repositoriesInCollections:3,repositoriesInZeroCollections:1,averageCollectionsPerSavedRepository:1.5}); });
  it("returns collection repository and deterministic distributions", async () => { const result=await new AnalyticsService(dependencies({CollectionModel:model([],[[{collectionId:"c",name:"Research",repositoryCount:3,repositories:[{source:"gitlab",language:null},{source:"github",language:"Go"},{source:"github",language:"Go"}]}]])})).collections(10); expect(result.collections[0]).toMatchObject({repositoryCount:3,sourceDistribution:[{value:"github",count:2},{value:"gitlab",count:1}],languageDistribution:[{value:"Go",count:2},{value:"Unknown",count:1}]}); });
  it("aggregates watchlist and monitored repository counts", async () => { const value=await new AnalyticsService(dependencies({WatchlistModel:model([3,2],[[]]),WatchlistMembershipModel:model([],[[{count:4}]]),WatchCheckRunModel:model([],[[],[]]),ChangeEventModel:model([], [[]])})).watchlists(range); expect(value).toMatchObject({totalWatchlists:3,enabledWatchlists:2,disabledWatchlists:1,monitoredRepositories:4}); });
  it("aggregates run statuses and rate-limited targets", async () => { const value=await new AnalyticsService(dependencies({WatchlistModel:model([1,1],[[]]),WatchlistMembershipModel:model([], [[]]),WatchCheckRunModel:model([],[[{_id:"completed",count:4,rateLimited:1},{_id:"partially_complete",count:2,rateLimited:3},{_id:"failed",count:1,rateLimited:0}],[]]),ChangeEventModel:model([], [[]])})).watchlists(range); expect(value).toMatchObject({successfulChecks:4,partialChecks:2,failedChecks:1,rateLimitedChecks:4}); });
  it("aggregates factual change types", async () => { const change=model([3],[[{_id:"stars",count:2}],[],[],[],[]]); expect((await new AnalyticsService(dependencies({ChangeEventModel:change})).changes(range)).changesByType).toEqual([{changeType:"stars",count:2}]); });
  it("aggregates change sources", async () => { const change=model([1],[[],[{_id:"github",count:1}],[],[],[]]); expect((await new AnalyticsService(dependencies({ChangeEventModel:change})).changes(range)).changesBySource).toEqual([{source:"github",count:1}]); });
  it("aggregates daily change timeline and unique counts", async () => { const change=model([2],[[],[],[{_id:"2026-01-02",count:2}],[{count:1}],[{count:1}]]); expect(await new AnalyticsService(dependencies({ChangeEventModel:change})).changes(range)).toMatchObject({changesByDay:[{date:"2026-01-02",count:2}],repositoriesWithChanges:1,watchlistsWithChanges:1}); });
  it("applies workspace and source filters to changes", async () => { const change=model([0],[[],[],[],[],[]]); await new AnalyticsService(dependencies({ChangeEventModel:change})).changes({...range,source:"github"}); expect(change.countDocuments).toHaveBeenCalledWith(expect.objectContaining({workspaceKey:"default",source:"github"})); });
  it("aggregates search statuses", async () => { const jobs=model([2],[[{_id:"completed",count:2}],[],[],[],[]]); expect((await new AnalyticsService(dependencies({SearchJobModel:jobs})).searches(range)).jobsByStatus).toEqual([{status:"completed",count:2}]); });
  it("aggregates collection modes and averages", async () => { const jobs=model([2],[[],[{_id:"deep",count:2}],[{value:4.5}],[],[]]); expect(await new AnalyticsService(dependencies({SearchJobModel:jobs})).searches(range)).toMatchObject({jobsByCollectionMode:[{collectionMode:"deep",count:2}],averagePersistedResultCount:4.5}); });
  it("scopes workspace-backed pipelines to default", async () => { const saved=model([0],[[],[],[]]); await new AnalyticsService(dependencies({SavedRepositoryModel:saved,CollectionMembershipModel:model([], [[]])})).saved(10); expect(saved.countDocuments).toHaveBeenCalledWith({workspaceKey:"default"}); expect(saved.aggregate.mock.calls[0][0][0]).toEqual({$match:{workspaceKey:"default"}}); });
});
