import express from "express";import request from "supertest";import {describe,expect,it,vi} from "vitest";import {createErrorHandler} from "../middleware/errorHandler.js";import {requestId} from "../middleware/requestId.js";import {createAIRouter} from "./ai.routes.js";
const id="507f191e810c19729de860aa";const service=()=>({status:vi.fn(async()=>({enabled:false,provider:"none",model:null,status:"disabled",capabilities:{}})),create:vi.fn(async(value:any)=>value),list:vi.fn(async()=>({sessions:[],nextCursor:null,hasMore:false})),get:vi.fn(async()=>({sessionId:id})),update:vi.fn(async(_id:string,value:any)=>value),remove:vi.fn(async()=>({deleted:true})),messages:vi.fn(async()=>({messages:[],nextCursor:null,hasMore:false})),generate:vi.fn(async()=>({assistant:{}}))});const app=(s:any,nodeEnv:"test"|"production"="test")=>{const value=express();value.use(express.json(),requestId,createAIRouter(s),createErrorHandler(nodeEnv));return value};
describe("AI routes",()=>{
 it("returns an honest disabled status without secrets",async()=>{const response=await request(app(service())).get("/status");expect(response.body).toMatchObject({success:true,data:{enabled:false,provider:"none",status:"disabled"},meta:{requestId:expect.any(String)}});expect(JSON.stringify(response.body)).not.toMatch(/key|token|authorization/i)});
 it("creates and renames validated sessions",async()=>{const s=service();expect((await request(app(s)).post("/sessions").send({title:"Research",contextSelection:{savedIds:[id]}})).status).toBe(201);expect((await request(app(s)).patch(`/sessions/${id}`).send({title:"Renamed"})).status).toBe(200)});
 it("lists sessions and loads messages with bounded pagination",async()=>{const s=service();expect((await request(app(s)).get("/sessions?limit=50")).status).toBe(200);expect((await request(app(s)).get(`/sessions/${id}/messages?limit=50`)).status).toBe(200);expect((await request(app(s)).get("/sessions?limit=51")).status).toBe(400)});
 it("deletes only the named AI session through the service boundary",async()=>{const s=service();expect((await request(app(s)).delete(`/sessions/${id}`)).body.data).toEqual({deleted:true});expect(s.remove).toHaveBeenCalledWith(id)});
 it("validates ObjectIds, message lengths, and client request IDs",async()=>{const s=service();expect((await request(app(s)).post("/sessions/not-an-id/messages").send({content:"q",clientRequestId:"request-1"})).status).toBe(400);expect((await request(app(s)).post(`/sessions/${id}/messages`).send({content:"x".repeat(4001),clientRequestId:"request-1"})).status).toBe(400);expect((await request(app(s)).post(`/sessions/${id}/messages`).send({content:"q",clientRequestId:"bad"})).status).toBe(400)});
 it("rejects excessive context selections",async()=>{const ids=Array.from({length:20},(_,i)=>`507f191e810c19729de8${String(i).padStart(4,"0")}`);const response=await request(app(service())).post("/sessions").send({title:"Too much",contextSelection:{savedIds:ids,changeIds:ids}});expect(response.status).toBe(400)});
 it("rejects client-selected generation token limits",async()=>{const s=service();const response=await request(app(s)).post(`/sessions/${id}/messages`).send({content:"Question",clientRequestId:"request-1",maxOutputTokens:4096});expect(response.status).toBe(400);expect(s.generate).not.toHaveBeenCalled()});
 it("sanitizes provider failures in production",async()=>{const s=service();s.generate=vi.fn(async()=>{throw new Error("provider body with secret")});const response=await request(app(s,"production")).post(`/sessions/${id}/messages`).send({content:"question",clientRequestId:"request-1"});expect(response.body).toMatchObject({success:false,error:{code:"INTERNAL_ERROR",message:"An unexpected error occurred"},meta:{requestId:expect.any(String)}});expect(JSON.stringify(response.body)).not.toContain("provider body")});
});
