import {afterEach,describe,expect,it,vi} from "vitest";import {aiFetch,aiJson} from "./core/http.js";import {AIProviderError,parseStructuredResponse} from "./core/aiProvider.js";import {LocalAIProvider} from "./providers/local.provider.js";import {NoneAIProvider} from "./providers/none.provider.js";import {OpenAIProvider} from "./providers/openai.provider.js";import {DeepSeekProvider} from "./providers/deepseek.provider.js";
const request=()=>({systemInstruction:"fixed",question:"compare",context:"[]",history:[],maxOutputTokens:777,signal:new AbortController().signal});afterEach(()=>vi.unstubAllGlobals());
describe("AI providers",()=>{
 it("supports AI_PROVIDER=none deterministically",async()=>{const provider=new NoneAIProvider();expect(await provider.health()).toEqual({status:"disabled"});await expect(provider.generate(request())).rejects.toMatchObject({code:"disabled"})});
 it("parses a successful local Ollama-compatible response",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({message:{content:JSON.stringify({answer:"Atlas fact",citations:[{citationId:"saved:1",claim:"fact"}],insufficientContext:false})}}),{status:200})));const result=await new LocalAIProvider("http://127.0.0.1:11434","atlas-local").generate(request());expect(result.answer).toBe("Atlas fact");expect(fetch).toHaveBeenCalledWith("http://127.0.0.1:11434/api/chat",expect.objectContaining({method:"POST"}))});
 it("classifies provider timeouts",async()=>{const controller=new AbortController();controller.abort();vi.stubGlobal("fetch",vi.fn(async()=>{throw new DOMException("aborted","AbortError")}));await expect(aiFetch("https://example.test",{},controller.signal)).rejects.toMatchObject({code:"timeout"})});
 it("classifies authentication failures",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response("denied",{status:401})));await expect(aiFetch("https://example.test",{},new AbortController().signal)).rejects.toMatchObject({code:"authentication"})});
 it("classifies provider rate limits",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response("limited",{status:429})));await expect(aiFetch("https://example.test",{},new AbortController().signal)).rejects.toMatchObject({code:"rate_limited"})});
 it("rejects malformed structured responses",()=>expect(()=>parseStructuredResponse("not-json")).toThrowError(AIProviderError));
 it("classifies malformed provider JSON bodies",async()=>{await expect(aiJson(new Response("not-json",{status:200}))).rejects.toMatchObject({code:"malformed"})});
 it("never returns external provider secrets in health metadata",async()=>{const openai=new OpenAIProvider("secret-value","configured-model"),deepseek=new DeepSeekProvider("other-secret","configured-model");expect(JSON.stringify([await openai.health(),await deepseek.health(),openai.model,deepseek.model])).not.toContain("secret")});
 it("caps OpenAI Responses generation with the configured token limit",async()=>{let body:any;vi.stubGlobal("fetch",vi.fn(async(_url:string,init:RequestInit)=>{body=JSON.parse(String(init.body));return new Response(JSON.stringify({output_text:JSON.stringify({answer:"Atlas fact",citations:[],insufficientContext:true}),usage:{input_tokens:2,output_tokens:3,total_tokens:5}}),{status:200})}));const result=await new OpenAIProvider("test-openai-secret","configured-model").generate(request());expect(body).toMatchObject({max_output_tokens:777,store:false});expect(body).not.toHaveProperty("max_tokens");expect(JSON.stringify(result)).not.toContain("test-openai-secret")});
 it("caps DeepSeek chat generation with the configured token limit",async()=>{let body:any;vi.stubGlobal("fetch",vi.fn(async(_url:string,init:RequestInit)=>{body=JSON.parse(String(init.body));return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({answer:"Atlas fact",citations:[],insufficientContext:true})}}]}),{status:200})}));const result=await new DeepSeekProvider("test-deepseek-secret","configured-model").generate(request());expect(body).toMatchObject({max_tokens:777});expect(body).not.toHaveProperty("max_output_tokens");expect(JSON.stringify(result)).not.toContain("test-deepseek-secret")});
 it("caps Ollama chat generation with num_predict",async()=>{let body:any;vi.stubGlobal("fetch",vi.fn(async(_url:string,init:RequestInit)=>{body=JSON.parse(String(init.body));return new Response(JSON.stringify({message:{content:JSON.stringify({answer:"Atlas fact",citations:[],insufficientContext:true})}}),{status:200})}));await new LocalAIProvider("http://127.0.0.1:11434","configured-model").generate(request());expect(body).toMatchObject({options:{num_predict:777},stream:false,format:"json"})});
});
