import { Types } from "mongoose";import { env } from "../../config/env.js";import { ChangeEventModel } from "../../models/changeEvent.model.js";import { CollectionMembershipModel,CollectionModel } from "../../models/collection.model.js";import { RepositoryResultModel } from "../../models/repositoryResult.model.js";import { SavedRepositoryModel } from "../../models/savedRepository.model.js";import { SearchJobModel } from "../../models/searchJob.model.js";import { WatchlistMembershipModel,WatchlistModel } from "../../models/watchlist.model.js";import { analyticsService } from "../analytics/analytics.service.js";
const workspaceKey="default";
export type ContextSelection={searchJobIds:string[];savedIds:string[];collectionIds:string[];watchlistIds:string[];changeIds:string[];includeAnalytics:boolean};
export type ContextSource={citationId:string;kind:"repository"|"saved"|"collection"|"watchlist"|"change"|"analytics"|"search";label:string;href:string|null;data:Record<string,unknown>};
export type BuiltContext={text:string;sources:ContextSource[];truncated:boolean;selectedCount:number;includedCount:number;missingReferences:string[]};
type Models=Record<string,any>;const defaults:Models={ChangeEventModel,CollectionMembershipModel,CollectionModel,RepositoryResultModel,SavedRepositoryModel,SearchJobModel,WatchlistMembershipModel,WatchlistModel};
const oid=(id:string)=>new Types.ObjectId(id);const safeRepo=(row:any)=>({source:row.source,owner:row.owner??null,fullName:row.fullName??row.name??null,description:row.description??null,repositoryUrl:row.repositoryUrl,language:row.language??null,languages:row.languages??[],topics:row.topics??[],stars:row.stars??null,forks:row.forks??null,watchers:row.watchers??null,openIssues:row.openIssues??null,license:row.license??null,archived:row.archived??null,fork:row.fork??null,visibility:row.visibility??null,createdAt:row.sourceCreatedAt??null,updatedAt:row.sourceUpdatedAt??null,pushedAt:row.pushedAt??null});
async function leanFind(model:any,filter:any,sort:any={_id:1},limit=100){if(limit<=0)return[];return model.find(filter).sort(sort).limit(limit).lean()}
export class ContextBuilderService{constructor(private models:Models=defaults,private analytics:any=analyticsService,private maxCharacters=24000,private maxRepositories=25){}
 async build(selection:ContextSelection):Promise<BuiltContext>{const sources:ContextSource[]=[],missing:string[]=[];let repositoryCount=0;const addRepo=(row:any,kind:"repository"|"saved",prefix:string,href:string)=>{if(repositoryCount>=this.maxRepositories)return false;repositoryCount++;sources.push({citationId:`${prefix}:${row._id}`,kind,label:row.fullName??row.name??`${row.source} repository`,href,data:{...safeRepo(row),...(kind==="saved"?{tags:row.tags??[]}:{})}});return true};
  if(selection.savedIds.length){const rows=await leanFind(this.models.SavedRepositoryModel,{_id:{$in:selection.savedIds.map(oid)},workspaceKey});const found=new Set(rows.map((x:any)=>String(x._id)));for(const id of selection.savedIds)if(!found.has(id))missing.push(`saved:${id}`);for(const row of rows)addRepo(row,"saved","saved",`/saved/${row._id}`)}
  if(selection.searchJobIds.length){const jobs=await leanFind(this.models.SearchJobModel,{_id:{$in:selection.searchJobIds.map(oid)}});const found=new Set(jobs.map((x:any)=>String(x._id)));for(const id of selection.searchJobIds)if(!found.has(id))missing.push(`search:${id}`);for(const job of jobs){sources.push({citationId:`search:${job._id}`,kind:"search",label:`Search: ${job.request?.query??"Untitled"}`,href:`/search?job=${job._id}`,data:{query:job.request?.query??null,status:job.status,totalUnique:job.totalUnique,collectionMode:job.request?.collectionMode??null,createdAt:job.createdAt}});const results=await leanFind(this.models.RepositoryResultModel,{jobId:job._id},{_id:1},Math.max(0,this.maxRepositories-repositoryCount));for(const row of results)addRepo(row,"repository","repo",`/search/jobs/${job._id}/repositories/${row._id}`)}}
  if(selection.collectionIds.length){const collections=await leanFind(this.models.CollectionModel,{_id:{$in:selection.collectionIds.map(oid)},workspaceKey});const found=new Set(collections.map((x:any)=>String(x._id)));for(const id of selection.collectionIds)if(!found.has(id))missing.push(`collection:${id}`);for(const collection of collections){sources.push({citationId:`collection:${collection._id}`,kind:"collection",label:collection.name,href:`/collections/${collection._id}`,data:{name:collection.name,description:collection.description}});const memberships=await leanFind(this.models.CollectionMembershipModel,{workspaceKey,collectionId:collection._id});const saved=memberships.length?await leanFind(this.models.SavedRepositoryModel,{workspaceKey,_id:{$in:memberships.map((x:any)=>x.savedId)}},{_id:1},Math.max(0,this.maxRepositories-repositoryCount)):[];for(const row of saved)addRepo(row,"saved","saved",`/saved/${row._id}`)}}
  if(selection.watchlistIds.length){const watchlists=await leanFind(this.models.WatchlistModel,{_id:{$in:selection.watchlistIds.map(oid)},workspaceKey});const found=new Set(watchlists.map((x:any)=>String(x._id)));for(const id of selection.watchlistIds)if(!found.has(id))missing.push(`watchlist:${id}`);for(const watch of watchlists){sources.push({citationId:`watchlist:${watch._id}`,kind:"watchlist",label:watch.name,href:`/watchlists/${watch._id}`,data:{name:watch.name,description:watch.description,enabled:watch.enabled,lastCheckedAt:watch.lastCheckedAt}});const memberships=await leanFind(this.models.WatchlistMembershipModel,{workspaceKey,watchlistId:watch._id});const saved=memberships.length?await leanFind(this.models.SavedRepositoryModel,{workspaceKey,_id:{$in:memberships.map((x:any)=>x.savedId)}},{_id:1},Math.max(0,this.maxRepositories-repositoryCount)):[];for(const row of saved)addRepo(row,"saved","saved",`/saved/${row._id}`)}}
  if(selection.changeIds.length){const changes=await leanFind(this.models.ChangeEventModel,{_id:{$in:selection.changeIds.map(oid)},workspaceKey});const found=new Set(changes.map((x:any)=>String(x._id)));for(const id of selection.changeIds)if(!found.has(id))missing.push(`change:${id}`);for(const row of changes)sources.push({citationId:`change:${row._id}`,kind:"change",label:`${row.source} change`,href:`/changes?change=${row._id}`,data:{source:row.source,externalId:row.externalId,detectedAt:row.detectedAt,changeTypes:row.changeTypes,changes:row.changes}})}
  if(selection.includeAnalytics){const to=new Date(),from=new Date(to.getTime()-30*86400000);const summary=await this.analytics.summary({from,to,limit:10});sources.push({citationId:"analytics:summary",kind:"analytics",label:"Atlas analytics summary",href:"/analytics?range=30d",data:{metrics:[{metric:"totalSearchJobs",value:summary.totalSearchJobs,definition:"persisted search_jobs records"},{metric:"totalCollectedRepositories",value:summary.totalCollectedRepositories,definition:"persisted repository_results records"},{metric:"savedRepositories",value:summary.savedRepositories,definition:"saved_repositories in the default workspace"},{metric:"recentChanges",value:summary.recentChanges,definition:"change_events in the last 30 days"}]}})}
  const selectedCount=selection.searchJobIds.length+selection.savedIds.length+selection.collectionIds.length+selection.watchlistIds.length+selection.changeIds.length+(selection.includeAnalytics?1:0);const uniqueSources=[...new Map(sources.map(source=>[source.citationId,source])).values()];const included:ContextSource[]=[];let length=2;for(const source of uniqueSources){const serialized=JSON.stringify(source);if(length+serialized.length+1>this.maxCharacters)break;included.push(source);length+=serialized.length+1}const truncated=included.length<uniqueSources.length||repositoryCount>=this.maxRepositories;return{text:JSON.stringify(included),sources:included,truncated,selectedCount,includedCount:included.length,missingReferences:missing}}
}
export const contextBuilderService=new ContextBuilderService(defaults,analyticsService,env.AI_CONTEXT_MAX_CHARACTERS,25);
