import {QueryClient,QueryClientProvider} from "@tanstack/react-query";import {cleanup,render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {MemoryRouter} from "react-router-dom";import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";import {AIResearchPage} from "./AIResearchPage";import * as api from "../services/api";
vi.mock("../services/api",()=>({aiStatus:vi.fn(),listAISessions:vi.fn(),createAISession:vi.fn(),listAIMessages:vi.fn(),sendAIMessage:vi.fn(),listSaved:vi.fn(),listCollections:vi.fn(),listSearchJobs:vi.fn(),listWatchlists:vi.fn()}));
const id="507f191e810c19729de860aa",savedId="507f191e810c19729de860ab";const status={enabled:true,provider:"local" as const,model:"atlas",status:"ready",capabilities:{groundedAnswers:true,citations:true,streaming:false}};const session={sessionId:id,title:"Agent research",contextSelection:{savedIds:[savedId],searchJobIds:[],collectionIds:[],watchlistIds:[],changeIds:[],includeAnalytics:false},createdAt:null,updatedAt:null};const assistant={messageId:"m2",role:"assistant" as const,content:"Grounded answer",citations:[{citationId:`saved:${savedId}`,claim:"fact",kind:"saved",label:"atlas/core",href:`/saved/${savedId}`}],provider:"local",model:"atlas",usage:{inputTokens:5,outputTokens:3,totalTokens:8},insufficientContext:false,grounded:true,contextTruncated:false,createdAt:null};
function setup(){vi.mocked(api.aiStatus).mockResolvedValue(status);vi.mocked(api.listAISessions).mockResolvedValue({sessions:[session],nextCursor:null,hasMore:false});vi.mocked(api.listAIMessages).mockResolvedValue({messages:[],nextCursor:null,hasMore:false});vi.mocked(api.listSaved).mockResolvedValue({repositories:[{savedId,fullName:"atlas/core"} as any],nextCursor:null,hasMore:false});vi.mocked(api.listCollections).mockResolvedValue([]);vi.mocked(api.listSearchJobs).mockResolvedValue({jobs:[],nextCursor:null,hasMore:false});vi.mocked(api.listWatchlists).mockResolvedValue({watchlists:[],nextCursor:null,hasMore:false});vi.mocked(api.createAISession).mockResolvedValue(session);vi.mocked(api.sendAIMessage).mockResolvedValue({user:{...assistant,messageId:"m1",role:"user",content:"Question",citations:[]},assistant,context:{truncated:false,selectedCount:1,includedCount:1,missingReferences:[]}})}
function view(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><MemoryRouter><AIResearchPage/></MemoryRouter></QueryClientProvider>)}beforeEach(()=>{setup();vi.stubGlobal("crypto",{randomUUID:()=>"request-1234"})});afterEach(()=>{cleanup();vi.clearAllMocks();vi.unstubAllGlobals()});
describe("AIResearchPage",()=>{
 it("renders the AI disabled state without an enabled chat box",async()=>{vi.mocked(api.aiStatus).mockResolvedValue({...status,enabled:false,provider:"none",model:null,status:"disabled"});view();expect(await screen.findByRole("heading",{name:"AI research is disabled"})).toBeInTheDocument();expect(screen.queryByLabelText("Research question")).not.toBeInTheDocument()});
 it("renders the AI loading state",()=>{vi.mocked(api.aiStatus).mockReturnValue(new Promise(()=>{}));view();expect(screen.getByText("Loading AI status...")).toBeInTheDocument()});
 it("renders a provider status error",async()=>{vi.mocked(api.aiStatus).mockRejectedValue(new Error("AI status unavailable"));view();expect(await screen.findByRole("alert")).toHaveTextContent("AI status unavailable")});
 it("renders the bounded session list",async()=>{view();expect(await screen.findByRole("button",{name:"Agent research"})).toBeInTheDocument()});
 it("creates a session with selected Atlas context",async()=>{view();await screen.findByText("atlas/core");await userEvent.type(screen.getByLabelText("Session title"),"New research");await userEvent.click(screen.getByLabelText("atlas/core"));await userEvent.click(screen.getByRole("button",{name:"Create session"}));await waitFor(()=>expect(api.createAISession).toHaveBeenCalledWith("New research",expect.objectContaining({savedIds:[savedId]})))});
 it("supports context selection, removal, and clear all",async()=>{view();await screen.findByText("atlas/core");await userEvent.click(screen.getByLabelText("atlas/core"));expect(screen.getByText("1/30 selected")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Clear all"}));expect(screen.getByText("0/30 selected")).toBeInTheDocument()});
 it("sends a bounded user message",async()=>{view();await userEvent.click(await screen.findByRole("button",{name:"Agent research"}));await userEvent.type(screen.getByLabelText("Research question"),"Compare the repository");await userEvent.click(screen.getByRole("button",{name:"Send question"}));await waitFor(()=>expect(api.sendAIMessage).toHaveBeenCalledWith(id,"Compare the repository","request-1234"))});
 it("renders persisted assistant responses",async()=>{vi.mocked(api.listAIMessages).mockResolvedValue({messages:[assistant],nextCursor:null,hasMore:false});view();await userEvent.click(await screen.findByRole("button",{name:"Agent research"}));expect(await screen.findByText("Grounded answer")).toBeInTheDocument()});
 it("renders validated Atlas citation chips",async()=>{vi.mocked(api.listAIMessages).mockResolvedValue({messages:[assistant],nextCursor:null,hasMore:false});view();await userEvent.click(await screen.findByRole("button",{name:"Agent research"}));expect(await screen.findByLabelText("Atlas citations")).toHaveTextContent("atlas/core")});
 it("links citations to the corresponding Atlas record",async()=>{vi.mocked(api.listAIMessages).mockResolvedValue({messages:[assistant],nextCursor:null,hasMore:false});view();await userEvent.click(await screen.findByRole("button",{name:"Agent research"}));expect(await screen.findByRole("link",{name:"atlas/core"})).toHaveAttribute("href",`/saved/${savedId}`)});
 it("renders insufficient-context responses honestly",async()=>{vi.mocked(api.listAIMessages).mockResolvedValue({messages:[{...assistant,citations:[],insufficientContext:true,grounded:true}],nextCursor:null,hasMore:false});view();await userEvent.click(await screen.findByRole("button",{name:"Agent research"}));expect(await screen.findByText("Available Atlas context was insufficient.")).toBeInTheDocument()});
 it("warns when context approaches the selection limit",async()=>{vi.mocked(api.listSaved).mockResolvedValue({repositories:Array.from({length:20},(_,i)=>({savedId:`507f191e810c19729de8${String(i).padStart(4,"0")}`,fullName:`atlas/repo-${i}`} as any)),nextCursor:null,hasMore:false});vi.mocked(api.listCollections).mockResolvedValue(Array.from({length:5},(_,i)=>({collectionId:`507f191e810c19729de9${String(i).padStart(4,"0")}`,name:`Collection ${i}`} as any)));view();await screen.findByText("atlas/repo-0");for(const checkbox of screen.getAllByRole("checkbox").slice(0,25))await userEvent.click(checkbox);expect(screen.getByText("Context is near the selection limit and may be truncated.")).toBeInTheDocument()});
});
