import {QueryClient,QueryClientProvider} from "@tanstack/react-query";import {cleanup,render,screen,within} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {MemoryRouter} from "react-router-dom";import {afterEach,describe,expect,it,vi} from "vitest";import {AnalyticsPage} from "./AnalyticsPage";
const summary={totalSearchJobs:12,completedSearchJobs:9,partiallyCompletedSearchJobs:1,totalCollectedRepositories:42,savedRepositories:5,collections:2,watchlists:3,recentChanges:4,enabledWatchlists:2,monitoredRepositories:4,lastSearchAt:null,lastSavedAt:null,lastChangeAt:null};
const payloads:Record<string,unknown>={summary,sources:{total:4,sources:[{source:"github",count:3,percentage:75},{source:"gitlab",count:1,percentage:25}],scope:"Atlas collected dataset"},languages:{total:3,excludedCount:0,languages:[{language:"TypeScript",count:2,percentage:66.67},{language:"Unknown",count:1,percentage:33.33}]},saved:{total:5,bySource:[],byLanguage:[],topTags:[{tag:"agents",count:2}],repositoriesInCollections:3,repositoriesInZeroCollections:2,averageCollectionsPerSavedRepository:1.2},watchlists:{totalWatchlists:3,enabledWatchlists:2,disabledWatchlists:1,monitoredRepositories:4,successfulChecks:8,partialChecks:2,failedChecks:1,rateLimitedChecks:3,mostRecentRunAt:null,watchlists:[]},changes:{totalChanges:3,changesByType:[{changeType:"stars",count:2},{changeType:"topics",count:1}],changesBySource:[{source:"github",count:3}],changesByDay:[{date:"2026-01-02",count:1},{date:"2026-01-03",count:2}],repositoriesWithChanges:2,watchlistsWithChanges:1,from:"",to:""}};
function mockFetch(options:{empty?:boolean;fail?:string}={}){vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);const key=Object.keys(payloads).find(name=>url.includes(`/api/analytics/${name}`))!;if(options.fail===key)return new Response(JSON.stringify({success:false,error:{message:`${key} unavailable`}}),{status:500});let data=payloads[key] as any;if(options.empty){data=key==="summary"?{...summary,totalSearchJobs:0,totalCollectedRepositories:0,savedRepositories:0,collections:0,watchlists:0,recentChanges:0}:key==="sources"?{...data,total:0,sources:[]}:key==="languages"?{...data,total:0,languages:[]}:key==="saved"?{...data,total:0,topTags:[]}:key==="watchlists"?{...data,totalWatchlists:0}:key==="changes"?{...data,totalChanges:0,changesByDay:[],changesByType:[]}:data;}return new Response(JSON.stringify({success:true,data}),{status:200});}));}
function view(entry="/analytics"){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[entry]}><AnalyticsPage/></MemoryRouter></QueryClientProvider>)}
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe("AnalyticsPage",()=>{
 it("renders independent loading states",()=>{vi.stubGlobal("fetch",vi.fn(()=>new Promise(()=>{})));view();expect(screen.getByText("Loading overview...")).toBeInTheDocument();expect(screen.getByText("Loading languages...")).toBeInTheDocument();});
 it("renders honest empty states",async()=>{mockFetch({empty:true});view();expect(await screen.findByText("No repository results have been collected yet.")).toBeInTheDocument();expect(screen.getByText("No changes have been detected in this period.")).toBeInTheDocument();});
 it("renders section API errors",async()=>{mockFetch({fail:"sources"});view();expect(await screen.findByRole("alert",{name:""})).toHaveTextContent("sources unavailable");});
 it("renders real summary cards",async()=>{mockFetch();view();expect(await screen.findByText("42")).toBeInTheDocument();expect(screen.getByText("Collected repositories")).toBeInTheDocument();expect(screen.getByText("Recent changes")).toBeInTheDocument();});
 it("renders source distribution counts and percentages",async()=>{mockFetch();view();const chart=await screen.findByRole("img",{name:"Atlas dataset source distribution"});expect(within(chart).getByText("3 (75%)")).toBeInTheDocument();});
 it("renders languages including Unknown",async()=>{mockFetch();view();const chart=await screen.findByRole("img",{name:"Top repository languages"});expect(within(chart).getByText("TypeScript")).toBeInTheDocument();expect(within(chart).getByText("Unknown")).toBeInTheDocument();});
 it("renders a factual change timeline",async()=>{mockFetch();view();const chart=await screen.findByRole("img",{name:"Changes by day"});expect(within(chart).getByText("2026-01-03")).toBeInTheDocument();expect(within(chart).getByText("2")).toBeInTheDocument();});
 it("renders monitoring summary",async()=>{mockFetch();view();expect(await screen.findByText("Successful checks")).toBeInTheDocument();expect(screen.getByText("Rate-limited targets")).toBeInTheDocument();});
 it("changes the bounded date-range filter",async()=>{mockFetch();view();await userEvent.selectOptions(screen.getByLabelText("Date range"),"90d");expect(screen.getByLabelText("Date range")).toHaveValue("90d");await vi.waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("from="),expect.anything()));});
 it("restores URL filters",async()=>{mockFetch();view("/analytics?range=365d&source=gitlab");expect(screen.getByLabelText("Date range")).toHaveValue("365d");expect(screen.getByLabelText("Source")).toHaveValue("gitlab");await vi.waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("source=gitlab"),expect.anything()));});
 it("keeps successful sections visible after a partial failure",async()=>{mockFetch({fail:"changes"});view();expect(await screen.findByText("Collected repositories")).toBeInTheDocument();expect(screen.getAllByText("changes unavailable")).toHaveLength(2);expect(screen.getByText("TypeScript")).toBeInTheDocument();});
 it("uses mobile-safe structural grids",async()=>{mockFetch();const {container}=view();expect(await screen.findByText("Collected repositories")).toBeInTheDocument();expect(container.querySelector(".analytics-grid")).toBeInTheDocument();expect(container.querySelector(".analytics-stats")).toBeInTheDocument();});
 it("exposes text and accessible labels for every chart",async()=>{mockFetch();view();expect(await screen.findByRole("img",{name:"Atlas dataset source distribution"})).toBeInTheDocument();expect(screen.getByRole("img",{name:"Changes by factual field"})).toHaveTextContent("stars");});
});
