import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { type FormEvent,useState } from "react";
import { Link,useSearchParams } from "react-router-dom";
import { addToCollection,listCollections,listSaved,removeFromCollection,unsaveRepository,updateSaved,workspaceSummary } from "../services/api";
import type { SavedRepository } from "../types/api";

export function SavedPage(){const client=useQueryClient();const [params,setParams]=useSearchParams();const [text,setText]=useState(params.get("text")??"");const cursor=params.get("cursor")??undefined;
 const saved=useQuery({queryKey:["saved",params.toString()],queryFn:()=>listSaved({cursor,text:params.get("text")??undefined,source:params.get("source")??undefined,language:params.get("language")??undefined,tag:params.get("tag")??undefined,collection:params.get("collection")??undefined}),retry:false});
 const collections=useQuery({queryKey:["collections"],queryFn:listCollections});
 const summary=useQuery({queryKey:["workspace-summary"],queryFn:workspaceSummary,retry:false});
 function filter(event:FormEvent){event.preventDefault();const next=new URLSearchParams(params);if(text.trim())next.set("text",text.trim());else next.delete("text");next.delete("cursor");setParams(next);}
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">Workspace library</span><h1>Saved repositories</h1><p>Workspace-wide saved research. Authentication and private ownership are not implemented yet.</p></div><strong>{summary.data?.savedRepositories??"—"} saved</strong></div>
 <form className="search-panel saved-filters" onSubmit={filter}><label><span>Search saved items</span><input value={text} onChange={e=>setText(e.target.value)} maxLength={100}/></label><label><span>Source</span><input value={params.get("source")??""} onChange={e=>{const n=new URLSearchParams(params);e.target.value?n.set("source",e.target.value):n.delete("source");setParams(n);}} placeholder="github"/></label><label><span>Language</span><input value={params.get("language")??""} onChange={e=>{const n=new URLSearchParams(params);e.target.value?n.set("language",e.target.value):n.delete("language");setParams(n);}}/></label><label><span>Tag</span><input value={params.get("tag")??""} onChange={e=>{const n=new URLSearchParams(params);e.target.value?n.set("tag",e.target.value):n.delete("tag");setParams(n);}}/></label><label><span>Collection</span><select value={params.get("collection")??""} onChange={e=>{const n=new URLSearchParams(params);e.target.value?n.set("collection",e.target.value):n.delete("collection");setParams(n);}}><option value="">All collections</option>{collections.data?.map(c=><option key={c.collectionId} value={c.collectionId}>{c.name}</option>)}</select></label><button className="button primary">Apply</button></form>
 {saved.isPending&&<div className="empty" role="status">Loading saved repositories…</div>}{saved.isError&&<div className="notice error" role="alert">{saved.error.message}</div>}{saved.data?.repositories.length===0&&<div className="empty"><h2>No saved repositories</h2><p>Save a repository from Universal Search to build this workspace library.</p></div>}
 {saved.data?.repositories.map(repository=><SavedCard key={repository.savedId} repository={repository} collections={collections.data??[]} currentCollection={params.get("collection")??undefined} refresh={()=>{void client.invalidateQueries({queryKey:["saved"]});void client.invalidateQueries({queryKey:["workspace-summary"]});}}/>)}
 {saved.data?.hasMore&&<button className="button" onClick={()=>{const n=new URLSearchParams(params);n.set("cursor",saved.data!.nextCursor!);setParams(n);}}>Next page</button>}</section>}

function SavedCard({repository,collections,currentCollection,refresh}:{repository:SavedRepository;collections:Array<{collectionId:string;name:string}>;currentCollection?:string;refresh:()=>void}){const [note,setNote]=useState(repository.note);const [tags,setTags]=useState(repository.tags.join(", "));const update=useMutation({mutationFn:()=>updateSaved(repository.savedId,{note,tags:tags.split(",").map(v=>v.trim()).filter(Boolean)}),onSuccess:refresh});const unsave=useMutation({mutationFn:()=>unsaveRepository(repository.savedId),onSuccess:refresh});const add=useMutation({mutationFn:(id:string)=>addToCollection(id,repository.savedId),onSuccess:refresh});const remove=useMutation({mutationFn:()=>removeFromCollection(currentCollection!,repository.savedId),onSuccess:refresh});
 return <article className="result-card"><div className="badges"><span className="source-badge">{repository.source}</span>{repository.language&&<span>{repository.language}</span>}</div><h2><Link to={`/saved/${repository.savedId}`}>{repository.fullName}</Link></h2><p>{repository.description||"No description supplied by the source."}</p><label><span>Workspace note</span><textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)}/></label><label><span>Tags, comma separated</span><input value={tags} onChange={e=>setTags(e.target.value)}/></label><div className="card-actions"><button className="button" onClick={()=>update.mutate()}>Save note and tags</button><select aria-label="Add to collection" defaultValue="" onChange={e=>{if(e.target.value)add.mutate(e.target.value);e.currentTarget.value=""}}><option value="">Add to collection…</option>{collections.map(c=><option key={c.collectionId} value={c.collectionId}>{c.name}</option>)}</select>{currentCollection&&<button className="button" onClick={()=>remove.mutate()}>Remove from current collection</button>}<a className="button" href={repository.repositoryUrl} target="_blank" rel="noopener noreferrer">Original source</a><button className="button danger" onClick={()=>{if(confirm(`Unsave ${repository.fullName}?`))unsave.mutate()}}>Unsave</button></div></article>}
