import {QueryClient,QueryClientProvider} from "@tanstack/react-query";import {cleanup,render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";import {MemoryRouter,Route,Routes} from "react-router-dom";
const api=vi.hoisted(()=>({getWatchlist:vi.fn(),listWatchedRepositories:vi.fn(),listWatchRuns:vi.fn(),listSaved:vi.fn(),addToWatchlist:vi.fn(),removeFromWatchlist:vi.fn(),checkWatchlist:vi.fn(),updateWatchlist:vi.fn()}));vi.mock("../services/api",()=>api);import {WatchlistDetailPage} from "./WatchlistDetailPage";
const wid="507f1f77bcf86cd799439011",sid="507f191e810c19729de860ea";
function renderPage(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[`/watchlists/${wid}`]}><Routes><Route path="/watchlists/:id" element={<WatchlistDetailPage/>}/></Routes></MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{vi.clearAllMocks();api.getWatchlist.mockResolvedValue({watchlistId:wid,name:"Core",description:"",enabled:true,checkIntervalMinutes:60,lastCheckedAt:null,nextCheckAt:null,targetCount:1});api.listWatchedRepositories.mockResolvedValue({repositories:[{savedId:sid,source:"github",externalId:"1",fullName:"atlas/core",lastCheckedAt:null,lastSuccessfulCheckAt:null,consecutiveFailures:0,lastError:null}],nextCursor:null,hasMore:false});api.listWatchRuns.mockResolvedValue({runs:[],nextCursor:null,hasMore:false});api.listSaved.mockResolvedValue({repositories:[{savedId:sid,source:"github",fullName:"atlas/core"}],nextCursor:null,hasMore:false});api.addToWatchlist.mockResolvedValue({});api.removeFromWatchlist.mockResolvedValue({deleted:true});api.checkWatchlist.mockResolvedValue({status:"completed"});api.updateWatchlist.mockResolvedValue({});});afterEach(cleanup);
describe("WatchlistDetailPage",()=>{
 it("adds and removes a saved repository",async()=>{renderPage();const user=userEvent.setup();await screen.findByRole("heading",{name:"Core"});await user.selectOptions(screen.getByRole("combobox"),sid);await user.click(screen.getByRole("button",{name:"Add"}));await waitFor(()=>expect(api.addToWatchlist).toHaveBeenCalledWith(wid,sid));await user.click(screen.getByRole("button",{name:"Remove"}));await waitFor(()=>expect(api.removeFromWatchlist).toHaveBeenCalledWith(wid,sid));});
 it("runs Check now for the current watchlist",async()=>{renderPage();const user=userEvent.setup();await user.click(await screen.findByRole("button",{name:"Check now"}));await waitFor(()=>expect(api.checkWatchlist).toHaveBeenCalledWith(wid));});
 it("renders safe provider failure health",async()=>{api.listWatchedRepositories.mockResolvedValue({repositories:[{savedId:sid,source:"github",externalId:"1",fullName:"atlas/core",lastCheckedAt:"2026-01-01",lastSuccessfulCheckAt:null,consecutiveFailures:3,lastError:{code:"rate_limited",category:"provider",occurredAt:"2026-01-01"}}],nextCursor:null,hasMore:false});renderPage();expect(await screen.findByText(/rate_limited · 3 consecutive failures/)).toBeInTheDocument();});
});
